In [1]:
import os
import torch
import numpy as np

In [2]:
path = '../../data/RotatedMNIST/raw/'

data = torch.load(os.path.join(path, 'RotatedMNIST.pt'))
group_idx = np.load(os.path.join(path, 'RotatedMNIST_group.npy'))

In [3]:
print(type(data))

<class 'list'>


In [4]:
print(len(data))

70000


In [5]:
print(type(data[0]))

<class 'dict'>


In [6]:
print(list(data[0].keys()))

['x', 'y', 'edge_index']


In [7]:
print(type(data[0]['x']))

<class 'torch.Tensor'>


In [8]:
print(data[0]['x'].shape)

torch.Size([73, 3])


In [9]:
print(data[0]['x'])

tensor([[0.0000, 0.3572, 0.9106],
        [0.5293, 0.7856, 0.2856],
        [0.0000, 0.5713, 0.0357],
        [0.0000, 0.2500, 0.0357],
        [0.0000, 0.7856, 0.9106],
        [0.0000, 0.2500, 0.7681],
        [0.0000, 0.4644, 0.0357],
        [0.0000, 0.9106, 0.4644],
        [0.0000, 0.3572, 0.0357],
        [0.0000, 0.0357, 0.2500],
        [0.9648, 0.6040, 0.3442],
        [0.0320, 0.5596, 0.2380],
        [0.0627, 0.5596, 0.9229],
        [0.0000, 0.3442, 0.2532],
        [0.8726, 0.1841, 0.4451],
        [0.7954, 0.2202, 0.3154],
        [0.0000, 0.6787, 0.1428],
        [0.8154, 0.3345, 0.6592],
        [0.0000, 0.4856, 0.4785],
        [0.0569, 0.0565, 0.3542],
        [0.7310, 0.7144, 0.3333],
        [0.0000, 0.8979, 0.2524],
        [0.0000, 0.0357, 0.1428],
        [0.0000, 0.0357, 0.0357],
        [0.0000, 0.7891, 0.1500],
        [0.8203, 0.6201, 0.4609],
        [0.9648, 0.6816, 0.2435],
        [0.0000, 0.6787, 0.0357],
        [0.0000, 0.9106, 0.7856],
        [0.000

In [10]:
print(data[0]['x'].dtype)

torch.float32


In [11]:
print(data[0]['y'].shape)

torch.Size([])


In [12]:
print(data[0]['y'])

tensor(2)


In [13]:
print(data[0]['y'].dtype)

torch.int64


In [12]:
print(data[0]['edge_index'].shape)

torch.Size([2, 584])


In [13]:
print(data[0]['edge_index'])

tensor([[ 0,  0,  0,  ..., 72, 72, 72],
        [56, 59, 48,  ...,  3, 13, 41]])


In [21]:
print(data[0]['edge_index'].dtype)

torch.int64


In [24]:
edge_index = data[0]['edge_index'].numpy()

In [29]:
np.where((edge_index[0] == 59) & (edge_index[1] == 0))

(array([474], dtype=int64),)

In [30]:
edge_index[:, 474]

array([59,  0], dtype=int64)

In [14]:
print(type(group_idx))

<class 'numpy.ndarray'>


In [16]:
print(group_idx.shape)

(70000,)


In [17]:
print(group_idx)

[0 0 0 ... 5 5 5]


In [18]:
print(group_idx.dtype)

int64
