In [1]:
import torch
import numpy as np

In [2]:
data = torch.load('SBM1.pt')
group_idx = np.load('SBM1_group.npy')

In [3]:
print(type(data))

<class 'list'>


In [4]:
print(len(data))

5000


In [5]:
print(type(data[0]))

<class 'dict'>


In [6]:
print(list(data[0].keys()))

['x', 'y', 'edge_index']


In [7]:
print(type(data[0]['x']))

<class 'torch.Tensor'>


In [8]:
print(data[0]['x'].shape)

torch.Size([91, 1])


In [9]:
print(data[0]['x'])

tensor([[1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [0.],
        [1.],
        [1.],
        [2.],
        [2.],
        [0.],
        [1.],
        [0.],
        [1.],
        [2.],
        [2.],
        [1.],
        [2.],
        [1.],
        [2.],
        [0.],
        [0.],
        [2.],
        [0.],
        [2.],
        [2.],
        [2.],
        [0.],
        [2.],
        [1.],
        [2.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [2.],
        [1.],
        [2.],
        [0.],
        [2.],
        [2.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [2.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [2.],
        [2.],
        [1.],
        [1.],
        [0.],
        [0.],
        [2.],
        [1.],
        [1.],
        [0.],
        [0.],
      

In [10]:
print(data[0]['x'].dtype)

torch.float32


In [11]:
print(data[0]['y'].shape)

torch.Size([])


In [12]:
print(data[0]['y'])

tensor(1)


In [13]:
print(data[0]['y'].dtype)

torch.int64


In [14]:
print(data[0]['edge_index'].shape)

torch.Size([2, 3554])


In [15]:
print(data[0]['edge_index'])

tensor([[ 0,  0,  0,  ..., 90, 90, 90],
        [ 1,  5,  8,  ..., 87, 88, 89]])


In [16]:
print(data[0]['edge_index'].dtype)

torch.int64


In [17]:
edge_index = data[0]['edge_index'].numpy()

In [18]:
np.where((edge_index[0] == 59) & (edge_index[1] == 0))

(array([2324], dtype=int64),)

In [19]:
edge_index[:, 474]

array([12, 21], dtype=int64)

In [20]:
print(type(group_idx))

<class 'numpy.ndarray'>


In [21]:
print(group_idx.shape)

(5000,)


In [22]:
print(group_idx)

[ 0  0  0 ... 49 49 49]


In [23]:
print(group_idx.dtype)

int64
